version: 2
jobs:
  build:
    docker:
      - image: vinodsharma/python:2.7-devel

    steps:

      - checkout

      - setup_remote_docker

      - run:
          name: Configure Docker Image Env Variable
          command: |
            echo 'export DOCKER_IMAGE=vinodsharma/circleci-demo-docker:$CIRCLE_SHA1' >> $BASH_ENV

      - run:
          name: Building Thestral Image
          command: |
            docker build -t  $DOCKER_IMAGE .

      - run:
          name: Running Tests
          command: |
            docker run -t $DOCKER_IMAGE python tests/test_*.py
